### PR TITLE
Fixes

### LINKED ISSUE #43: Bug fixes and improvement
1. Add casting to `String` for `active` field when building xls for clients and products.
2. Remove hard delete of clients and products.
3. Move secrets to env variables.

### PR DESCRIPTION
**Pull request by volodymyrvynnyk**

### CODE REVIEW

File: src/main/java/com/pnu/ordermanagementapp/service/ClientServiceImpl.java [hunk 1]
```diff
@@ -94,12 +94,8 @@ public void update(ClientFormSubmitDto clientFormDto, Long userId) {
     @Override
     public void delete(Long id, Long userId) {
```
Comment (Igor-Polatajko) [inline src/main/java/com/pnu/ordermanagementapp/service/ClientServiceImpl.java]: On my opinion this methods better to be renamed to `deactivate`.

**Review by Igor-Polatajko — APPROVED** [review]
Good!
One minor comment

File: src/main/java/com/pnu/ordermanagementapp/view/ProductsExcelView.java [hunk 2]
```diff
@@ -37,7 +37,7 @@ protected void buildExcelDocument(Map<String, Object> model, Workbook workbook,
             courseRow.createCell(idx++).setCellValue(product.getName());
             courseRow.createCell(idx++).setCellValue(product.getAmount());
             courseRow.createCell(idx++).setCellValue(product.getPrice());
-            courseRow.createCell(idx++).setCellValue(product.isActive());
+            courseRow.createCell(idx++).setCellValue(String.valueOf(product.isActive()));
```
Comment (Igor-Polatajko) [inline src/main/java/com/pnu/ordermanagementapp/view/ProductsExcelView.java]: Can be better to have something like `product.isActive() ? "active" : "inactive"`

File: src/main/resources/templates/product/show_products.ftl [hunk 3]
```diff
@@ -90,10 +90,6 @@
                         <button class="btn btn-primary" type="submit">Activate</button>
                         <input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}"/>
                     </form>
```
Comment (Igor-Polatajko) [inline src/main/resources/templates/product/show_products.ftl:93]: Please, also set appropriate `<title>`s for pages in scope of this PR.
For example `<title>Products</title>` for products and so on.
